name: lol_lcu
channels:
  - defaults

dependencies:
  - python=3.12
  - pip
  - pip:
    - lcu-driver
    - requests
    - psutil==5.6.5
    - pandas
    - rich
    - sqlalchemy
    - mysql-connector-python
    - pyqt5
